import {promises as fs} from "fs"
import path from "node:path"
import fg from "fast-glob"
import {optimize} from "svgo"
import {load} from "cheerio"

export interface SpriteOptions {
  iconDir: string
  svgoConfig?: any
}

export interface SpriteResult {
  sprite: string
  symbols: string[]
  iconCount: number
}

export async function generateSprite(options: SpriteOptions): Promise<SpriteResult> {
  const {iconDir, svgoConfig} = options
  
  const svgFiles = await fg("**/*.svg", {
    cwd: iconDir,
    absolute: true
  })

  const symbols = await Promise.all(
    svgFiles.map(async file => {
      const content = await fs.readFile(file, "utf-8")

      // Cheerio를 사용해 원본 속성 추출
      const $original = load(content)
      const $originalSvg = $original("svg")
      const viewBox = $originalSvg.attr("viewBox") || "0 0 24 24"
      const fill = $originalSvg.attr("fill")

      const {data} = optimize(content, {
        path: file,
        plugins: [
          {
            name: "preset-default",
            params: {
              overrides: {
                removeViewBox: false,
                removeUselessStrokeAndFill: false,
                removeUnknownsAndDefaults: false,
                ...svgoConfig?.overrides
              }
            }
          }
        ]
      })

      // 최적화된 SVG의 내부 컨텐츠만 추출
      const $optimized = load(data)
      const symbolContent = $optimized("svg").html() || ""
      const iconName = path.basename(file, ".svg")

      // 보존된 속성으로 symbol 생성
      const fillAttr = fill ? ` fill="${fill}"` : ""
      return `<symbol id="icon-${iconName}" viewBox="${viewBox}"${fillAttr}>${symbolContent}</symbol>`
        .replace(/\s{2,}/g, " ")
        .trim()
    })
  )

  const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">${symbols.join("")}</svg>`

  return {
    sprite,
    symbols,
    iconCount: symbols.length
  }
}

export function createInlineScript(sprite: string): string {
  return `
    const sprite = \`${sprite}\`;
    const container = document.createElement('div');
    container.id = '__svg_sprite_container__';
    container.innerHTML = sprite;
    document.body.insertBefore(container, document.body.firstChild);
  `
}

export function createIIFEScript(sprite: string): string {
  return `// Generated by vite-plugin-svg-sprite-builder\n` +
    `(function(){\n` +
    `  if (typeof document === 'undefined') return;\n` +
    `  var containerId = '__svg_sprite_container__';\n` +
    `  if (document.getElementById(containerId)) return;\n` +
    `  var container = document.createElement('div');\n` +
    `  container.id = containerId;\n` +
    `  container.innerHTML = ${JSON.stringify(sprite)};\n` +
    `  document.body.insertBefore(container, document.body.firstChild);\n` +
    `})();\n`
}